version: '3.8'

services:
  paysavvy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: node server.js
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=paysavvy
      - POSTGRES_USER=paysavvy_user
      - POSTGRES_PASSWORD=secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paysavvy_user -d paysavvy"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: